---

  pipelines:
    default:
      - step:
          image: centos:7
          script:
            # create variable shorthands
            - export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
            - export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
            - export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}"

            # install AWS CLI and configure it
            - yum install --assumeyes "epel-release"
            - yum install --assumeyes "python-pip"
            - pip install "awscli"
            - aws configure set preview.cloudfront true

            # push static files to AWS S3
            - aws s3 sync "./" "s3://${S3_BUCKET}/" --exclude '.*' --exclude 'bitbucket-pipelines.yml' --acl "public-read"

            # trigger CloudFront refresh
            - aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_ID}" --paths "/*"

            # notify!
            - echo "Static files have been pushed to ${S3_BUCKET}."
